# Generated by Django 6.0.7 on 2026-07-27 19:29

from django.db import migrations, models


def rename_role_forward(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='managing_director').update(role='admin')


def rename_role_backward(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    User.objects.filter(role='admin').update(role='managing_director')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operations_manager', 'Operations Manager'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('finance_officer', 'Finance Officer')], default='technician', max_length=30),
        ),
        migrations.RunPython(rename_role_forward, rename_role_backward),
    ]
