# Generated by Django 6.0.7 on 2026-08-09 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_alter_user_managers_user_company'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_status_007c84_idx',
        ),
        migrations.RemoveIndex(
            model_name='job',
            name='jobs_job_assigne_2b05bf_idx',
        ),
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company'),
        ),
        migrations.AddField(
            model_name='jobcategory',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_categories', to='accounts.company'),
        ),
        migrations.AlterField(
            model_name='jobcategory',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'status', 'priority'], name='jobs_job_company_f78367_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['company', 'assigned_to', 'status'], name='jobs_job_company_adbcb3_idx'),
        ),
        migrations.AddConstraint(
            model_name='jobcategory',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uniq_category_per_company'),
        ),
    ]
