# Generated by Django 6.0.7 on 2026-08-09 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_company_alter_user_managers_user_company'),
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='accounts.company'),
        ),
    ]
